@startuml "Use Cases"
left to right direction
actor User
package Select {
    usecase "List Apps with Assessment status" as list
    usecase "Select 1 App" as selectapp
}
package Copy {
    usecase "Select FROM app" as selectfrom
    usecase "Select TO app" as selectto
    usecase "Copy Assessment" as copyfromto
}
package Assess {
    usecase "Select Stakeholders" as selectstake
    usecase "Answer Questions" as answer
}
package Answer {
    usecase "Navigate Questions Categories" as navigate
    usecase "Save as Draft" as save
    usecase "Select option as answer" as select
    usecase "Add comment" as comment
    usecase "See question explanation" as explana
}
package Review {
    usecase "Select completed Assessment" as selectassessment
    usecase review as "Set action, effort,
    criticallity, priority, comments"
    usecase "see assessment summary" as summary
}
package Report {
    usecase "Select Report" as selectreport
}


User --> selectapp
User --> selectstake

User --> answer
User --> list
User --> copyfromto
User ..> selectfrom
User ..> selectto

answer ..> navigate : include
answer ..> save : include
answer ..> select : include
answer ..> comment : include
answer ..> explana : include

User --> review
User --> summary
User --> selectassessment
User --> selectreport
@enduml
