'
' Copyright © 2021 Konveyor (https://konveyor.io/)
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'     http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
'

@startuml "Use Cases Design"
left to right direction
actor User
package Design {
    usecase "Add/Edit/Delete Questionaire" as addquestionaire
    usecase "Add/Edit/Delete question" as addquestion
    usecase "Add/Edit/Delete answer" as addanswer
    usecase "Import Questionaire" as import
    usecase "Export Questionaire" as export
}
package Translation {
    usecase "Add/Edit/Delete text in Base language" as addtext
    usecase "Add/Edit/Delete translated text" as translate
}
User --> addquestionaire
addquestionaire ..> addquestion : include
addquestion ..> addanswer : include
User --> import
User --> export
User --> addtext
User --> translate
@enduml
